-- Supabase 테이블 생성 스크립트

-- 1. 사용자 테이블 (auth.users 테이블은 이미 Supabase에서 제공)
CREATE TABLE IF NOT EXISTS public.users (
  id UUID PRIMARY KEY REFERENCES auth.users(id),
  email TEXT UNIQUE NOT NULL,
  name TEXT,
  role TEXT DEFAULT 'USER',
  profile_image TEXT,
  phone_number TEXT,
  bank_info JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. 게시물 테이블
CREATE TABLE IF NOT EXISTS public.posts (
  id BIGINT PRIMARY KEY,
  title TEXT NOT NULL,
  content TEXT,
  price INTEGER,
  status TEXT DEFAULT 'ACTIVE',
  user_id UUID REFERENCES public.users(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. 알림 테이블
CREATE TABLE IF NOT EXISTS public.notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.users(id),
  post_id BIGINT REFERENCES public.posts(id),
  message TEXT NOT NULL,
  type TEXT NOT NULL,
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- RLS(Row Level Security) 정책 설정
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

-- 사용자 테이블 정책
CREATE POLICY "사용자는 자신의 정보만 수정 가능" ON public.users
  FOR UPDATE USING (auth.uid() = id);
  
CREATE POLICY "모든 사용자 정보는 조회 가능" ON public.users
  FOR SELECT USING (true);

-- 게시물 테이블 정책
CREATE POLICY "게시물은 누구나 조회 가능" ON public.posts
  FOR SELECT USING (true);
  
CREATE POLICY "게시물은 작성자만 수정 가능" ON public.posts
  FOR UPDATE USING (auth.uid()::text = user_id::text);
  
CREATE POLICY "게시물은 작성자만 삭제 가능" ON public.posts
  FOR DELETE USING (auth.uid()::text = user_id::text);

-- 알림 테이블 정책
CREATE POLICY "사용자는 자신의 알림만 조회 가능" ON public.notifications
  FOR SELECT USING (auth.uid()::text = user_id::text);
  
CREATE POLICY "사용자는 자신의 알림만 수정 가능" ON public.notifications
  FOR UPDATE USING (auth.uid()::text = user_id::text);

-- 인덱스 생성
CREATE INDEX IF NOT EXISTS idx_posts_user_id ON public.posts(user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON public.notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_post_id ON public.notifications(post_id); 